import localFont from "next/font/local";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Footer from "./components/Footer";
import Header from "./components/Header";
config.autoAddCss = false
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar`}
      >
        <div className="bg-gradient-to-tr from-black via-black to-indigo-900 text-white font-mono">
          <Header />
          <div className="px-6 lg:px-40 pt-16 pb-8">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
